#!/bin/bash

echo "🧪 Тестування оновлення фінансової панелі після покупок..."
echo ""
echo "📋 Інструкції для тестування:"
echo ""
echo "1. ✅ Відкрийте гру в браузері: http://localhost:5173"
echo "2. ✅ Запустіть Developer Console (F12)"
echo "3. ✅ Почніть нову гру в Developer Mode"
echo ""
echo "🔍 Що перевіряти:"
echo ""
echo "ПЕРЕД покупкою активу:"
echo "   💰 Готівка (Cash): запишіть поточну суму"
echo "   📈 Пасивний дохід (Passive Income): запишіть суму"
echo "   🏠 Кількість активів: запишіть кількість"
echo ""
echo "ПІСЛЯ покупки активу:"
echo "   ✅ Готівка повинна ЗМЕНШИТИСЬ на суму покупки"
echo "   ✅ Пасивний дохід повинен ЗБІЛЬШИТИСЬ на cashFlow активу"
echo "   ✅ Кількість активів повинна збільшитись на 1"
echo ""
echo "🐛 Якщо числа НЕ змінились - значить баг ще є!"
echo ""
echo "📊 Логи які треба шукати в консолі:"
echo "   - '💰 CellEffects: Buying deal'"
echo "   - '✅ CellEffects: Deal bought successfully'"
echo "   - '🎮 Updated currentPlayer:'"
echo ""
echo "🔄 Для перезапуску сервісів:"
echo "   npm run dev:restart"
